### ISSUE TITLE
Trouble with MODE_CCM

### ISSUE THREAD

**Issue by andys8** [DrMcCoy/tg3442_firewall#3]
## Issue

```shell
Traceback (most recent call last):
  File "tg3442_firewall.py", line 184, in <module>
    main()
  File "tg3442_firewall.py", line 151, in main
    login(session, url, username, password)
  File "tg3442_firewall.py", line 66, in login
    cipher = AES.new(key, AES.MODE_CCM, binascii.unhexlify(iv))
AttributeError: module 'Crypto.Cipher.AES' has no attribute 'MODE_CCM'
```

## Solution

Worked for me

```shell
pip uninstall pycrypto
pip install pycryptodomex
```

Maybe add a line in the readme or have a descriptive error message like this one.

<https://github.com/r4sas/PBinCLI/commit/19f130feb1e8e228a3511b57f5cb10862fed7632>

Script otherwise seems to be working. Thanks.

**Comment by DrMcCoy** [comment]
Yeah, see #1.

You're right, I need to add a note in the README, forgot about that, sorry about that :)

**Comment by DrMcCoy** [comment]
Okay, added a note to the README.md, and an error message to the script itself. :)
